### PR TITLE
耿雪萌(root g)&肖欣语

### PR DESCRIPTION
**Pull request by rootG**
This is the first version of our LinkLink.

### CODE REVIEW

**Comment by ccreimondo** [comment]
你就删啦？

**Comment by ccreimondo** [comment]
image

😅

**Comment by rootG** [comment]
不能删嘛？  我还以为弄到主线就可以删了...

**Comment by ccreimondo** [comment]
可以删的

On Sun, Jun 14, 2015 at 5:10 PM, 耿雪萌 <notifications@github.com> wrote:

> 不能删嘛？ 我还以为弄到主线就可以删了...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wecontinue/Hackthon/pull/1#issuecomment-111804772>.
>



-- 
MAIL: mio@reimondo.org
Let's make the world a fairy tale

**Pull request merged**
